name: etrick
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  provider: ^6.0.5
  go_router: ^7.1.1
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.2.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  collection: ^1.17.1
  flutter_local_notifications: ^14.1.1
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/categories/